import './globals.css';
import jwt from 'jsonwebtoken';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getParsedCookie } from '../util/cookies';
import { ApolloClientProvider } from './ApolloClientProvider';
import Signout from './Signout.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userDataRaw = await getParsedCookie();
  console.log('userDataRaw: ', userDataRaw);
  const userData =
    typeof userDataRaw === 'string'
      ? ((await jwt.decode(userDataRaw)) as string)
      : null;
  console.log('userData: ', userData);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full bg-gray-300 flex flex-row z-10 justify-around h-10 items-center">
          <div className="flex ">Logo</div>
          <div className="flex flex-row gap-20">
            <Link href="/">Feed</Link>
            <Link href="/">DAOs</Link>
            <Link href="/">About Us</Link>
          </div>
          {!userData ? (
            <div className="flex flex-row gap-20">
              <Link href={{ pathname: '/login' }} passHref>
                Login
              </Link>
              <Link href={{ pathname: '/signup' }} passHref>
                Signup
              </Link>
            </div>
          ) : (
            <div className="flex ">
              <Link href={{ pathname: '/profile' }} passHref>
                My Profile
              </Link>
              <Signout />
            </div>
          )}
        </nav>
        <ApolloClientProvider>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
