import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { checkLogin } from '../util/auth';
import { ApolloClientProvider } from './ApolloClientProvider';
import Signout from './Signout.js';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = await cookies().get('sessionToken');
  const loggedIn = await checkLogin(token);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full bg-gray-300 flex flex-row z-10 justify-around h-10 items-center">
          <div className="flex ">Logo</div>
          <div className="flex flex-row gap-14">
            <Link href="/">Feed</Link>
            <Link href="/">DAOs</Link>
            <Link href="/">About Us</Link>
          </div>
          {loggedIn === false ? (
            <div className="flex flex-row gap-14">
              <Link href={{ pathname: '/login' }} passHref>
                Login
              </Link>
              <Link href={{ pathname: '/signup' }} passHref>
                Signup
              </Link>
            </div>
          ) : (
            <div className="flex flex-row justify-around">
              <Link
                href={{ pathname: '/profile' }}
                className="flex flex-row gap-20"
                passHref
              >
                My Profile
              </Link>
              <div className="ml-10">
                <Signout />
              </div>
            </div>
          )}
        </nav>
        <ApolloClientProvider>{children}</ApolloClientProvider>
      </body>
    </html>
  );
}
